#pragma once
#include "Color.hpp"
#include <map>

namespace pandemic
{
    enum City
    {
        Algiers,
        Atlanta,
        Baghdad,
        Bangkok,
        Beijing,
        Bogota,
        BuenosAires,
        Cairo,
        Chennai,
        Chicago,
        Delhi,
        Essen,
        HoChiMinhCity,
        HongKong,
        Istanbul,
        Jakarta,
        Johannesburg,
        Karachi,
        KePasio,
        Khartoum,
        Kinshasa,
        Kolkata,
        Lagos,
        Lima,
        London,
        LosAngeles,
        Madrid,
        Manila,
        MexicoCity,
        Miami,
        Milan,
        Montreal,
        Moscow,
        Mumbai,
        NewYork,
        Osaka,
        Paris,
        Riyadh,
        SanFrancisco,
        Santiago,
        SaoPaulo,
        Seoul,
        Shanghai,
        StPetersburg,
        Sydney,
        Taipei,
        Tehran,
        Tokyo,
        Washington
    };

    const std::map<City, Color> cities_color{
        {Algiers, Black},
        {Atlanta, Blue},
        {Baghdad, Black},
        {Bangkok, Red},
        {Beijing, Red},
        {Bogota, Yellow},
        {BuenosAires, Yellow},
        {Cairo, Black},
        {Chennai, Black},
        {Chicago, Blue},
        {Delhi, Black},
        {Essen, Blue},
        {HoChiMinhCity, Red},
        {HongKong, Red},
        {Istanbul, Black},
        {Jakarta, Red},
        {Johannesburg, Yellow},
        {Karachi, Black},
        {Khartoum, Yellow},
        {Kinshasa, Yellow},
        {Kolkata, Black},
        {Lagos, Yellow},
        {Lima, Yellow},
        {London, Blue},
        {LosAngeles, Yellow},
        {Madrid, Blue},
        {Manila, Red},
        {MexicoCity, Yellow},
        {Miami, Yellow},
        {Milan, Blue},
        {Montreal, Blue},
        {Moscow, Black},
        {Mumbai, Black},
        {NewYork, Blue},
        {Osaka, Red},
        {Paris, Blue},
        {Riyadh, Black},
        {SanFrancisco, Blue},
        {Santiago, Yellow},
        {SaoPaulo, Yellow},
        {Seoul, Red},
        {Shanghai, Red},
        {StPetersburg, Blue},
        {Sydney, Red},
        {Taipei, Red},
        {Tehran, Black},
        {Tokyo, Red},
        {Washington, Blue},
    };

}
